### ISSUE TITLE
Autolint broken after Neomake update

### ISSUE THREAD

**Issue by rkiyanchuk** [dojoteef/neomake-autolint#13]
Today after updating Vim plugins I started to get the following error from `neomake-autolint` plugin on startup:

```
Error detected while processing function neomake#autolint#Startup[12]..neomake#autolint#Setup[11]..neomake#autolint#buffer#makers:
line   12:
E15: Invalid expression: l:ft.'_'.l:maker_name.'_autolint'
Press ENTER or type command to continue
```

Knowing that it worked with identical configuration just couple of hours ago I looked for recent updates to related plugins and was able to pinpoint Neomake commit that broke Autolint: [28559e](https://github.com/neomake/neomake/commit/28559ed0e575aca6addbace534c0851143bc70c9)

It seems the behavior of [neomake#GetEnabledMakers](https://github.com/neomake/neomake/commit/28559ed0e575aca6addbace534c0851143bc70c9#diff-1ceaba5126b0cf477e72f87cb2767af0R468) function has changed causing Autolint to crash.

I'm not too good with VimL, so couldn't come up with the fix right away.

**Comment by dojoteef** [comment]
@zoresvit @carlitux I submitted the following fix: 11ce867. It works for me locally. If this does not address the problem for you please let me know.
