### ISSUE TITLE
ESLint "no-unresolved" rule 

### ISSUE THREAD

**Issue by whossname** [dojoteef/neomake-autolint#16]
When using ESLint for javascript the "no-unresolved" rule will throw an error in autolint while neomake says it is fine. Neomake is correct, the code works. 

The eslint "no-unresolved" rule ensures that imported modules can be resolved to a module on the local filesystem.

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md

This isn't particularly important, but if you guys have an idea as to why this is happening I might try to find a work around for it.

**Comment by dojoteef** [comment]
@whossname Sorry for the late response, I've been a little preoccupied lately. I have a suspicion is this an example of Neomake Autolint not referencing your *.eslintrc*.  See [this comment](https://github.com/dojoteef/neomake-autolint/issues/6#issuecomment-279186164) for a suggestion on how to fix the issue.

**Comment by whossname** [comment]
I have no idea what this is even about anymore. Might as well close it.

**Comment by whossname** [comment]
I've got an idea of how I resolved this now. The explanation of eslint in this readme helped a lot https://github.com/jaxbot/syntastic-react
