### ISSUE TITLE
Autolint only for editable files

### ISSUE THREAD

**Issue by DerWeh** [dojoteef/neomake-autolint#18]
By default `neomake-autolint` lints all files, also help files for vim.
To my mind it would make more sense to only work on files which are `modifiable` and not `readonly`.
Of course you can work around with some if statements in your `init.vim file`, but I think a plug-in option would be saner.

**Comment by blueyed** [comment]
For Neomake's automaking (WIP at https://github.com/neomake/neomake/pull/1167) I've thought about having some callback / config to configure this, and therefore this feedback is useful for it.
I am currently only handling empty `&buftype` there, which works for help files like you would expect it.

In general I was thinking about using a black- and whitelist for filetypes and buftypes.

btw: I am setting `modifiable` for my help files explicitly:
```
    " Vim help files: modifiable (easier to edit for typo fixes); buflisted
    " for easier switching to them.
    au FileType help setl modifiable buflisted
```

I have many local changes for https://github.com/neomake/neomake/pull/1167, but plan to work on this during the next days (i.e. push them).

**Comment by dojoteef** [comment]
The README now clearly states the plugin is deprecated (I haven't actually had the time to update it for a while now anyway, sorry). If you are having any issues please try Neomake's builtin automake functionality.
