### ISSUE TITLE
[FEATURE REQUEST] Choose the neomake's maker to be run

### ISSUE THREAD

**Issue by bstaletic** [dojoteef/neomake-autolint#2]
I'm using neomake to run make in my current project, but I'm using a custom defined maker that looks like this:
```VimL
let g:neomake_c_armgcc_maker={
    \  'exe': 'arm-none-eabi-gcc', 
    \ 'args': [ '-Os', '-g', '-Wall', '-Wextra', '-Wno-main', '-pedantic', '-x', 'c', '-std=c99', '-DSTM32F4', '-DSTM32F407VG', '-DSTM32F4CCM', '-I.', '-Ilibopencm3/include', '-c', ],
     \ 'errorformat': '%f:%l:%c: %m', }
```
So I'm actually using `:Neomake armgcc`. I would like the option to tell neomake-autolint which of the neomake's makers to run.

Thanks in advance.

**Comment by dojoteef** [comment]
Could you try adding this to your vimrc: `let g:neomake_c_enabled_makers = ['armgcc']`

**Comment by bstaletic** [comment]
I have just tried using that line and it solved the issue. Funny thing is, I thought I read the neomake's documentation carefully. I guess there's nothing to be done here, so I'll close the issue.
