### ISSUE TITLE
NeomakeAutolintToggle feedback

### ISSUE THREAD

**Issue by DerWeh** [dojoteef/neomake-autolint#21]
In my opinion `NeomakeAutolintToggle` should echo a status message, weather it was dis- or enabled.

**Comment by blueyed** [comment]
As for Neomake's toggle commands I've made them to only display something if `&verbose` is on, e.g. with `:verb NeomakeToggleBuffer`.
But i understand from this issue (and common sense) that it makes sense to have feedback there - even though I think general feedback through the statusline (soon to land in Neomake) is better in general.
Ref: https://github.com/neomake/neomake/pull/1428.

**Comment by blueyed** [comment]
In general, I think we should focus now on getting what neomake-autloint provides into Neomake soonish, and things like that belong to that.
Just for reference (again), the PR for automaking / config setup is https://github.com/neomake/neomake/pull/1167.

**Comment by blueyed** [comment]
Neomake supports automaking by now itself.. :fireworks:

**Comment by dojoteef** [comment]
The README now clearly states the plugin is deprecated (I haven't actually had the time to update it for a while now anyway, sorry). If you are having any issues please try Neomake's builtin automake functionality.
