### ISSUE TITLE
Autolint don't work even following FAQ suggestions

### ISSUE THREAD

**Issue by caneta** [dojoteef/neomake-autolint#22]
I've followed every suggestion on "[Neomake Autolint is not working](https://github.com/dojoteef/neomake-autolint#neomake-autolint-is-not-working)" section of the README, but the lint-as-you-type feature don't shows up anyway.

I'm writing JavaScript and when I save a buffer, Automake runs Eslint and I can see errors and warnings.

What am I missing?

Thank you!

**Comment by blueyed** [comment]
Neomake supports automaking by now itself.. :fireworks:

**Comment by dojoteef** [comment]
The README now clearly states the plugin is deprecated (I haven't actually had the time to update it for a while now anyway, sorry). If you are having any issues please try Neomake's builtin automake functionality.

**Comment by caneta** [comment]
Could you please give a little hint on how to configure this feature in Neomake now?
Thanks

**Comment by blueyed** [comment]
@caneta 
See https://github.com/neomake/neomake/#setup.

There is also `:h neomake.txt`.
