### ISSUE TITLE
Difference to `neomake`  48df73ff790214bd95619c1696d2bed81c96a09b

### ISSUE THREAD

**Issue by DerWeh** [dojoteef/neomake-autolint#23]
I think with this [commit](https://github.com/neomake/neomake/commit/48df73ff790214bd95619c1696d2bed81c96a09b) `neomake` offers the same functionality as this plugin now.

Should this plug-in be depreciated or are there some preseasons to keep using `neomake-autolint` additionally to `neomakes`'s automake?

**Comment by blueyed** [comment]
Yes, Neomake's automaking should make this plugin obsolete by now.

**Comment by DerWeh** [comment]
Thanks for the info. The plug-in was really helpful. Then I will go over to the built-in solution.
Maybe this information should be added to the readme.

**Comment by dojoteef** [comment]
Great suggestion. The README now clearly states the plugin is deprecated (I haven't actually had the time to update it for a while now anyway).
