### ISSUE TITLE
autolint seems to be incompatible with lazy loading via vim-plug

### ISSUE THREAD

**Issue by alok** [dojoteef/neomake-autolint#3]
I lazy-load neomake to cut startup-time a little, and i have these two lines

```vim
Plug 'https://github.com/neomake/neomake',                        { 'on': ['Neomake']}
Plug 'https://github.com/dojoteef/neomake-autolint',              { 'on': ['Neomake']}
```

If I delete the `on` part, autolint works fine, but it seems to be disabled if I try to use the above config. Is there a way to make it work with lazy-loading?

**Comment by dojoteef** [comment]
I verified locally that 3b6c25c addresses your issue. Closing this for now.

**Comment by alok** [comment]
I tried out the new commit, and it does pick up the changes to my file automatically, but it also doesn't show anything in the sign column, even though `sign_column_always=1`.

**Comment by dojoteef** [comment]
I cannot seem to replicate your issue. Neomake Autolint should have no effect on what is shown in the sign column. The flag `g:neomake_autolint_sign_column_always` only determines if the sign column should always be shown not what is shown in it.

Can you verify that using that using [Neomake](https://github.com/neomake/neomake) without Neomake Autolint does indeed show signs? For example I know in my case the default highlighting that [Neomake](https://github.com/neomake/neomake) chose for the signs made it such that I could not see some of the signs. I had to do manually change the highlighting as described in the [Neomake documentation](https://github.com/neomake/neomake/blob/3a41cd2/doc/neomake.txt).

Here's how I did it:

```
  autocmd vimrc ColorScheme,VimEnter *
         \ highlight! link NeomakeErrorSign Error
         \ | highlight! link NeomakeWarningSign Debug
```

You can use `:highlight` to see the list of available highlights or you can specify your own. Check the vim documentation for more info.

**Comment by alok** [comment]
Running `PlugClean` and `PlugInstall` seemed to fix it. I'll be damned if I know why though. Thanks for the quick commit to fix this.
