### ISSUE TITLE
move gif out of repo

### ISSUE THREAD

**Issue by bounceme** [dojoteef/neomake-autolint#4]
it is fairly large at almost 1/2 mb. could you find another host for it?

**Comment by dojoteef** [comment]
I'm sorry, but at this point I think it's more trouble than it's worth to remove a 500kb from the repo. Even if I remove it from the master branch it'll still be there in the repository. The only way to truly remove it would likely require all users to re-clone the repository, which I'm not willing to do.

If you are on a system where 500kb is somehow too much disk space (I can't imagine how that would be the case), you could always make your own fork of the repository on Github, remove the gif, then when you clone your repository just use `git clone --depth=1`. That would only truncate the history such that you get the latest branch without the 500kb gif. Good luck!

**Comment by blueyed** [comment]
`git clone --depth=1` is a valid/common pattern for cloning plugins, and therefore removing it from the repo would help in those cases already.

While it's not that much in current times, it's also not necessary to replicate it to all users computers after all.
Given that there are 10 users (according to the stars) currently, that's already 5mb of data not needed.. ;)
