### ISSUE TITLE
Requesting option for when linting occurs

### ISSUE THREAD

**Issue by emiasims** [dojoteef/neomake-autolint#8]
Right now autolint runs the linter every time I change the text, but I would prefer if it only linted on exiting insert mode. Can you and an option for that?

**Comment by dojoteef** [comment]
@mtszyk Can I ask why you want it only on exiting insert mode? Is there some issue you are trying to solve?

**Comment by emiasims** [comment]
To clarify, on change text while not in insert mode, and when exiting insert mode. I would just rather the linting occur when I'm in normal mode, not while I'm inserting text.

**Comment by dojoteef** [comment]
Okay, I understand when you want linting to occur. My question is why you
prefer that. The reason I ask is to see if the already existing features
address your underlying concern.

For example does simply increasing the idle time before linting occurs to
5, 10, 15 seconds or more address your reason for wanting linting to occur
upon leaving insert mode or changing text while not in insert mode.

While you state you want it to occur only on exiting insert mode and text
changed while not in insert mode, at times that can cause frequent linting.
For example search and replace or when making minor changes. If you are
trying to limit the frequency of linting, simply making it always lint in
those cases will not address that concern.

So what is your reasoning for not linting while in insert mode?

**Comment by blueyed** [comment]
Sounds sensible to me to make the list of autoevent configurable (https://github.com/dojoteef/neomake-autolint/blob/68e4bf79aae977abc27d59465b1cc5d130a5966b/autoload/neomake/autolint.vim#L136).
Timers would still be applied then.

When exiting insert mode (`InsertLeave`) however, it might make sense to use another/no timer then, but rather start linting directly.
This could be simulated however by calling `:Neomake` manually on that event.
It might be better to provide an interface from neomake-autolint however, e.g. similar to `neomake#autolint#update` (but where the `bufinfo` should default to the current buffer then).

**Comment by emiasims** [comment]
I don't see any benefit to linting while in insert mode, since when I'm insert mode I'm actively changing the text. Why bother checking for errors when I know that I'm still editing the text? I'm necessarily in normal mode when I want to see the results of the linting.

I love the behavior of the plugin outside of insert mode, though, so would want to keep that (with, for example, the default autolint update time), so I wouldn't be triggering the overly frequent linting like you mentioned.

**Comment by dojoteef** [comment]
@blueyed Thanks, I really like your approach of configuring which events would trigger linting. My concern is to try to keep the amount of configuration options to a minimum so that hopefully the maintainability is high and the plugin does not have a bewildering number of options for users.

For example [ALE] has [options](https://github.com/w0rp/ale#4viii-how-can-i-run-linters-only-when-i-save-files) for linting on save, on enter buffer, and while in insert mode. Having separate options for each means each time someone wants to lint on a different event they need to add an additional option which reduces maintainability. That's my main reason for asking questions to get to the root concern rather than immediately adding a feature, even if the feature might be quick and or trivial to add.

[ALE]: https://github.com/w0rp/ale

**Comment by blueyed** [comment]
What about a dict where the keys are the events, mapped to a dict with options, where only `delay` would be used from for now (and defaults to the existing setting for it)?

The described use case could then be configured like this:

```vim
let g:neomake_autolint_events = {
  \ 'BufWinEnter': {},
  \ 'TextChanged': {},
  \ 'InsertLeave': {'delay': 0}
  \ }
```

**Comment by dojoteef** [comment]
I was thinking something along the same lines, with the addition of a `neomake#autolint#Now(...)` function that either lints the current buffer or an optionally provided bufnr.

**Comment by dojoteef** [comment]
This should now be possible, let me know if you run into any issues.
